### ISSUE TITLE
zhiyuan_aws_assignment

### ISSUE THREAD

**Issue by gao-ti** [trilogy-group/tu2k22-zhiyuangao#10]

**Comment by gao-ti** [comment]
# Milestone 1

![image](https://user-images.githubusercontent.com/110180090/184351291-fec9e55f-decc-43fa-a93b-ceadd2db05f7.png)

**Comment by gao-ti** [comment]
## Milestone 2

### Step 1 & Step 3

![image](https://user-images.githubusercontent.com/110180090/184371195-72dcf467-6b58-4f71-a38c-7b96f062089e.png)

### Step 2

![image](https://user-images.githubusercontent.com/110180090/184371468-df97baae-5584-4a5e-b7c7-60c124e3b9e2.png)


![image](https://user-images.githubusercontent.com/110180090/184371582-3202bb2a-7261-431e-8607-3086ad6df025.png)

**Comment by gao-ti** [comment]
### Step 4

```
aws sts assume-role --profile saml --role-arn "arn:aws:iam::280022023954:role/zhiyuan-introaws"  --role-session-name zhiyuan-introaws
```

![image](https://user-images.githubusercontent.com/110180090/184378930-5b7a03b9-0c97-49b1-90c4-59637c0be3b5.png)

### Step 5

```
aws s3 --profile saml ls s3://zhiyuangao --recursive --human-readable --summarize
```

![image](https://user-images.githubusercontent.com/110180090/184381190-fd8ab6b0-f38c-48fb-8823-b3ba3291e2a0.png)

**Comment by gao-ti** [comment]
### Milestone 3 

Video https://ui.weave.aurea.com/video/2427

#### Step 1
```
s3 = boto3.client('s3',
            aws_access_key_id=Credentials['AccessKeyId'],
            aws_secret_access_key=Credentials['SecretAccessKey'],
            aws_session_token=Credentials['SessionToken']
        )
with open(file_name, "rb") as f:
    s3.upload_fileobj(f, "zhiyuangao", "test_obj_name")
```
![image](https://user-images.githubusercontent.com/110180090/184391485-686ecb53-dd0b-4262-b691-c672079cd353.png)

**Comment by gao-ti** [comment]
### step 2

First create sns topic

Then create s3 event

![image](https://user-images.githubusercontent.com/110180090/184395772-046d6152-61a6-4a98-ad97-bb87159f4096.png)

Ref https://docs.aws.amazon.com/AmazonS3/latest/userguide/ways-to-add-notification-config-to-bucket.html

**Comment by gao-ti** [comment]
## Milestone 4

https://ui.weave.aurea.com/video/2428
#### Step 1
![image](https://user-images.githubusercontent.com/110180090/184476397-b0907533-41f9-4f75-b5e8-2abcc27d5874.png)
![image](https://user-images.githubusercontent.com/110180090/184476428-0eedee64-43f9-48cd-9d19-4ebcc9a00c52.png)

#### Step 2
![image](https://user-images.githubusercontent.com/110180090/184476466-fd785989-a20d-4422-93ae-6e3992922611.png)

![image](https://user-images.githubusercontent.com/110180090/184476522-4bcef60a-2db3-4572-b067-89087275e035.png)

#### Step 3
![image](https://user-images.githubusercontent.com/110180090/184476555-b42b33db-e474-4aea-9915-e42bab4eaec2.png)



### Step 4

![image](https://user-images.githubusercontent.com/110180090/184476338-64bbcd59-5cc7-46a5-80cd-faa72c377c96.png)
![image](https://user-images.githubusercontent.com/110180090/184476359-28cf8f7e-3560-4b51-a0e5-fc968bfc0564.png)

**Comment by sirjan-cn** [comment]
Record a video for M3 and M4

**Comment by gao-ti** [comment]
## Bonus

#### 1. Given daily logs from an App, how would you want to save in S3 for it to be economical to search in terms of time and cost from S3. Explain what you did and Why?

**Answer:** Daily logs from an app can include multiple dimensions
- It can be RDS query logs --> in this case it can be stored in a table in RDS, and can be easily accessed through queries. This is useful especially when we hope to learn about e.g., long queries in an RDS instance.
- It can be the logs of the backend server on an EC2 instance -- in this case, the monitor logs can be analysed using AWS CloudWatch 
- for the traces/error logs and other logs that are uploaded to S3 -- we can use Amazon Athena to query the logs.

It is best to keep logs connected to cloudwatch, and keep logs outside of the cloudwatch minimum.

**Comment by gao-ti** [comment]
![image](https://user-images.githubusercontent.com/110180090/184492918-57528988-363a-4b48-a96f-9d45851c2b86.png)

So when it comes to Milestone 4 step 4, 
I created an endpoint for sns communication, then copied my saml credentials.
This shows that I can communicate with sns without problem
![image](https://user-images.githubusercontent.com/110180090/184492921-a0dd5ef9-9a82-42e8-8ca4-8cd2c0fe51e6.png)
