### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by gao-ti** [trilogy-group/tu2k22-zhiyuangao#19]
Frontend
- [x] milestone 1: route53 to s3 static hosting
- [x] milestone 2: route53 to cloudfront where origin is s3
Backend
- [x] milestone 1
- [x] milestone 2
Github Action
- [x]

**Comment by gao-ti** [comment]
## Frontend milestone 1

![image](https://user-images.githubusercontent.com/110180090/185368894-16ce811e-d565-4907-9647-9e942ce6a894.png)
![image](https://user-images.githubusercontent.com/110180090/185368967-c216563c-abf1-4d83-bc66-0fe5e7779300.png)

**Comment by gao-ti** [comment]
## Frontend Milestone 2

![image](https://user-images.githubusercontent.com/110180090/185378400-39a6c678-87cb-4ae8-a831-cd06090c799a.png)


![image](https://user-images.githubusercontent.com/110180090/185378547-40fbcb54-5232-4ec5-a745-2bd5d221b0d8.png)

![image](https://user-images.githubusercontent.com/110180090/185378592-262f5d3d-607a-4bbb-b7bc-837e09bf6422.png)

**Comment by gao-ti** [comment]
## Backend Milestone 1


![image](https://user-images.githubusercontent.com/110180090/185380560-06342839-255d-4592-a6c4-dbcef5b771e0.png)


![image](https://user-images.githubusercontent.com/110180090/185380612-62ecdb0d-23ee-4ca4-b5fe-ea0fcc91ec9f.png)
![image](https://user-images.githubusercontent.com/110180090/185380654-c1d5aa0e-81bf-4498-a880-c36a7f2ff29c.png)

**Comment by gao-ti** [comment]
## Milestone 2 

![image](https://user-images.githubusercontent.com/110180090/186239957-292fe8e9-7f02-409a-b70c-4f4ff341783f.png)

![elb](https://user-images.githubusercontent.com/110180090/186240139-ac7e5621-fd3b-40b1-874f-eadbf63803d6.JPG)

**Comment by gao-ti** [comment]
## Added github actions for milestone 3
* Build and push the new container image
* restart the container

# Questions for Frontend Milestone 2

### Security, apply certificate
<img src="https://user-images.githubusercontent.com/110180090/185601664-51cf1c2c-9822-41dd-9c40-8c6161872fa6.png" alt="drawing" width="600"/>

<img src="https://user-images.githubusercontent.com/110180090/185602631-306a3fc1-c968-43e5-82c4-67f680caf346.png" alt="drawing" width="600"/>

### Why cloudfront? -- The benefits of CDN 
* Caching, reducing loading time/latency. reducing the traffic going into e.g., my s3 static website
* can be connected to load balancer so we don't expose load balancer to the user
* Do DDoS/firewall things

### Always use **latest image**
![image](https://user-images.githubusercontent.com/110180090/185601080-a62c5840-c007-47f1-94b5-d903b0fd3df0.png)

### How ecs tasks get permissions ( difference between two roles)

I spent some time on this, did not find much useful documentation. Can you give me a document to read?

### How resources are managed across the ecs tasks

If containers try to consume memory between the soft limit and a hard limit, they may compete with each other. 
--> Linux kernel’s OOM (Out of Memory) killer

For CPU resources, an EC2 host that has 8 vCPUs has 8×1024=8192 units available. 

if containers are not using their allotted CPU units, other containers can use that capacity. When capacity is not used, any container can burst to use that spare capacity. CPU shares control the amount of CPU capacity available when there is CPU contention; that is, multiple containers attempting to use the CPU at the same time.

if there is spare capacity on the host (because the sum of all CPU units across all containers across all tasks is less than the available capacity on the host) the excess capacity on the host is re-partitioned proportionally to all of the containers if/when they need it

https://aws.amazon.com/blogs/containers/how-amazon-ecs-manages-cpu-and-memory-resources/

###  Figure out target group registration automatically

After you attach a target group to an Auto Scaling group, Auto Scaling registers your targets with the target group for you when it launches them

https://stackoverflow.com/questions/59398798/automatically-registering-targets-with-a-target-group-in-aws

**Comment by sirjan-cn** [comment]
Left with showing load balancer working, @gao-ti attach a screenshot when you are able to access the endpoint

GH Action needs to be fixed too

**Comment by gao-ti** [comment]
![image](https://user-images.githubusercontent.com/110180090/186241483-b7506c11-aa04-4374-bf0f-979755d7e744.png)
https://github.com/trilogy-group/tu2k22-zhiyuangao/actions/runs/2914017030
