### ISSUE TITLE
zhiyuangao-graphdb-neo4j

### ISSUE THREAD

**Issue by gao-ti** [trilogy-group/tu2k22-zhiyuangao#26]

**Comment by gao-ti** [comment]
https://github.com/gao-ti/neo4j-sb2.0.9R-j11-maven-in-docker-query

**Comment by gao-ti** [comment]
![image](https://user-images.githubusercontent.com/110180090/186750787-e52e7930-262d-488c-a59b-62def47ab691.png)

**Comment by sirjan-cn** [comment]
Add all queries to the issue
