### ISSUE TITLE
DL assignment

### ISSUE THREAD

**Issue by gao-ti** [trilogy-group/tu2k22-zhiyuangao#27]
- [x] milestone 1
- [x] milestone 2
- [x] milestone 3

https://github.com/trilogy-group/tu2k22-zhiyuangao/tree/dl

**Comment by gao-ti** [comment]
![image](https://user-images.githubusercontent.com/110180090/186981383-69fc8222-8ca8-42d4-95a4-9fc5611a79c8.png)

**Comment by gao-ti** [comment]
![image](https://user-images.githubusercontent.com/110180090/186982840-e057a208-0d7d-48c6-90b4-712cfe5455f1.png)
![image](https://user-images.githubusercontent.com/110180090/186982865-3e52ab4a-ae06-496d-8cb5-0f0ad0a0cb8a.png)

**Comment by gao-ti** [comment]
![image](https://user-images.githubusercontent.com/110180090/186985268-bce085eb-6b6a-4f5a-9cea-2986c295a2a5.png)


![image(1)](https://user-images.githubusercontent.com/110180090/186983168-a5da651b-d771-4692-a95d-8cd4b1b8ba17.png)

**Comment by gao-ti** [comment]
* LSTM networks are a type of RNN that uses special units in addition to standard units. LSTM units include a 'memory cell' that can maintain information in memory for long periods of time. This memory cell lets them learn longer-term dependencies.

#### attention
basic lstm gets confused between the words and sometimes can predict the wrong word. So whenever this type of situation occurs the encoder step needs to search for the most relevant information, this idea is called 'Attention'. 
https://analyticsindiamag.com/hands-on-guide-to-bi-lstm-with-attention/


Epochs
One Epoch is when an ENTIRE dataset is passed forward and backward through the neural network only ONCE.


divide dataset into Number of Batches or sets or parts.
Batch Size
Total number of training examples present in a single batch.

**Comment by kushal-ti** [comment]
why is you predicted closing price and the actual closing price off by so much
the graph should have been more or less overlapping for the two

**Comment by gao-ti** [comment]
@kushal-ti 
In my analysis, the closing price fluctuates at around 90~140 on a daily basis, the prediction line now falls at around, or slightly above the 5-day average of the closing price.

So instead of a per-day prediction, it looks like a prediction of a e.g., 5-day average.

That must have something to do with my training, but not totally sure about it.

**Comment by kushal-ti** [comment]
okay, this has been approved for now, so i'd suggest you move on to other tasks
