### ISSUE TITLE
react instructions

### ISSUE THREAD

**Issue by gao-ti** [trilogy-group/tu2k22-zhiyuangao#6]
https://github.com/trilogy-group/tu2k22-zhiyuan-stock-market

**Comment by gao-ti** [comment]
![counter](https://user-images.githubusercontent.com/110180090/184134716-bd6861f8-2113-447e-b2af-60de3ec49a65.JPG)
![couter_decrease](https://user-images.githubusercontent.com/110180090/184134720-21dd6075-3d46-4ab5-a71b-4146b911c8c8.JPG)

**Comment by gao-ti** [comment]
https://ui.weave.aurea.com/video/2389

**Comment by gao-ti** [comment]
![image](https://user-images.githubusercontent.com/110180090/184135593-383c1886-085d-4769-bed1-a5a98c45d06d.png)

**Comment by sirjan-cn** [comment]
LGTM
