### ISSUE TITLE
Observability -intro

### ISSUE THREAD

**Issue by gao-ti** [trilogy-group/tu2k22-zhiyuangao#7]
Running prom from docker 

![image](https://user-images.githubusercontent.com/110180090/184210473-bc6cc078-2872-4acf-b4f1-d8854e8d4a77.png)
![image](https://user-images.githubusercontent.com/110180090/184210517-ded67684-5e7e-4270-ad12-1df7fbd89590.png)

**Comment by gao-ti** [comment]
jaegur

![image](https://user-images.githubusercontent.com/110180090/184210823-28eb6dcd-be9e-47ad-9142-7a6e8b608e31.png)

![image](https://user-images.githubusercontent.com/110180090/184210849-92f3d85c-d2d4-48ec-ae96-f3101377ad3a.png)
![image](https://user-images.githubusercontent.com/110180090/184210904-48cd5713-4741-481f-8018-94fd0c62ae66.png)

**Comment by sirjan-cn** [comment]
- [x] Jaegar
- [x] Prometheus
- [ ] Unit Test the Match Order API

**Comment by gao-ti** [comment]
@sirjan-cn 
Tests on the match order api created!

https://github.com/trilogy-group/tu2k22-zhiyuangao/commit/c81e738fd25083f3d8380ce5f229677b4fbe6a36
