### ISSUE TITLE
AWS Intro

### ISSUE THREAD

**Issue by gao-ti** [trilogy-group/tu2k22-zhiyuangao#9]
![image](https://user-images.githubusercontent.com/110180090/184308659-1597d1f2-3d20-4684-aae8-4c52fe5f46af.png)
![image](https://user-images.githubusercontent.com/110180090/184308696-354961ea-aa17-45fa-8e2b-8e8dac93e81b.png)

**Comment by gao-ti** [comment]
![image](https://user-images.githubusercontent.com/110180090/184308953-53b28f73-c017-413a-addd-a099aef500c3.png)
![image](https://user-images.githubusercontent.com/110180090/184309888-50bf2362-f68b-45ea-801e-226be577c92a.png)



### SNS

**Comment by sirjan-cn** [comment]
Email message is not what was told in instructions

**Comment by gao-ti** [comment]
![image](https://user-images.githubusercontent.com/110180090/184310466-d2654f15-99ff-4625-9e05-0fe0fd46057e.png)

**Comment by gao-ti** [comment]
![image](https://user-images.githubusercontent.com/110180090/184311858-27c2f074-c336-496e-931f-c8666dfb15d3.png)

**Comment by sirjan-cn** [comment]
LGTM, Please delete all the above resources now

**Comment by gao-ti** [comment]
already removed!
